  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: react-build
        path: dist/

    - name: Prepare Deployment Folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/html/bank-frontend
          sudo chown -R $USER:$USER /var/www/html/bank-frontend
          sudo chmod -R 755 /var/www/html/bank-frontend

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/html/bank-frontend"

    - name: Set Permissions for Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R ubuntu:www-data /var/www/html/bank-frontend
          sudo chmod -R 755 /var/www/html/bank-frontend

    - name: Reload Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "🔄 Reloading Nginx..."
          sudo nginx -s reload
