name: Deploy React App to EC2 using PM2

on:
  push:
    branches: ["tahir"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: react-build
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: react-build
        path: dist/  

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/html/bank-frontend"

    - name: Start Application with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Set permissions for dist folder
          sudo chown -R ubuntu:www-data /var/www/html/bank-frontend/dist
          sudo chmod -R 755 /var/www/html/bank-frontend/dist
      
    - name: Verify PM2 Process
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          #sudo pm2 list
          echo "🔄 Reloading Nginx..."
          sudo nginx -s reload